default_stages: [pre-commit, pre-push]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-yaml
          - id: sort-simple-yaml
          - id: check-added-large-files

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.1.0"
      hooks:
          - id: prettier
