# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["main"]
    # Allow triggering the workflow manually and in check_for_new_obsidian.yaml
    workflow_dispatch:

permissions: {}

jobs:
    test-desktop:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    # Enable these if you want to test your plugin on different platforms
                    # - windows-latest
                    # - macos-latest
        runs-on: ${{ matrix.os }}
        name: Test ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "25.x"
                  cache: "npm"

            - run: npm ci
            - run: npm run build

            - name: Run unit tests
              run: npm run test:unit

            # Get key to use for the .obsidian-cache GitHub cache. Run wdio.conf.mts directly,
            # which will logs the Obsidian versions to test (see the `if (process.env.CI)` bit
            # in wdio.conf.mts). We'll use that output as the cache key.
            - name: "Get Obsidian cache key"
              run: |
                  npx tsx wdio.conf.mts | grep 'obsidian-cache-key:' > obsidian-versions-lock.txt
                  # Delete the cache created by wdio.conf.mts so it doesn't conflict with restore
                  rm -rf .obsidian-cache
              env:
                  # Beta versions require an Obsidian Insiders account to download. If you want to
                  # test beta versions, you'll need add your credentials to GitHub secrets as
                  # OBSIDIAN_EMAIL and OBSIDIAN_PASSWORD. 2FA needs to be disabled.
                  # Note that workflows triggered by fork PRs won't have access to GitHub secrets.
                  OBSIDIAN_EMAIL: ${{ secrets.OBSIDIAN_EMAIL }}
                  OBSIDIAN_PASSWORD: ${{ secrets.OBSIDIAN_PASSWORD }}

            - name: Cache Obsidian
              uses: actions/cache@v4
              with:
                  path: .obsidian-cache
                  key: obsidian-cache-${{ matrix.os }}-${{ hashFiles('obsidian-versions-lock.txt') }}

            # On linux runners we need to set up a virtual graphics stack for Obsidian. Here we
            # use xvfb as a virtual display server and herbstluftwm as the window manager. (You
            # can sometimes get by without the window manager, but some Obsidian features won't
            # work properly wihtout it.)
            - if: ${{ matrix.os == 'ubuntu-latest' }}
              name: "Setup virtual graphics"
              run: |
                  # Some hacks to speed up apt install
                  sudo rm -rf /etc/apt/sources.list.d/*.list
                  echo "set man-db/auto-update false" | sudo debconf-communicate
                  sudo dpkg-reconfigure man-db

                  sudo apt-get update -q
                  sudo apt-get install -q herbstluftwm dzen2 x11-xserver-utils

                  export DISPLAY=:99
                  echo "DISPLAY=$DISPLAY" >> "$GITHUB_ENV"
                  Xvfb $DISPLAY -screen 0 1280x1024x24 +extension GLX -noreset &
                  sleep 1
                  herbstluftwm &
                  sleep 1

            - name: Run e2e tests
              run: npm run test:e2e
              env:
                  WDIO_MAX_INSTANCES: 2 # Github runners are 2-core
                  OBSIDIAN_EMAIL: ${{ secrets.OBSIDIAN_EMAIL }}
                  OBSIDIAN_PASSWORD: ${{ secrets.OBSIDIAN_PASSWORD }}

    # This makes it easier to require all tests to pass on PRs. Just set the final "check" job as
    # required in the GitHub repo settings instead of having to manually set every matrix combination
    check:
        if: always()
        needs: [test-desktop]
        runs-on: ubuntu-latest
        steps:
            - name: Check all tests passed
              uses: re-actors/alls-green@release/v1
              with:
                  jobs: ${{ toJSON(needs) }}
